// Code generated by go-swagger; DO NOT EDIT.

package cloud

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDomainDomainParams creates a new GetDomainDomainParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDomainDomainParams() *GetDomainDomainParams {
	return &GetDomainDomainParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDomainDomainParamsWithTimeout creates a new GetDomainDomainParams object
// with the ability to set a timeout on a request.
func NewGetDomainDomainParamsWithTimeout(timeout time.Duration) *GetDomainDomainParams {
	return &GetDomainDomainParams{
		timeout: timeout,
	}
}

// NewGetDomainDomainParamsWithContext creates a new GetDomainDomainParams object
// with the ability to set a context for a request.
func NewGetDomainDomainParamsWithContext(ctx context.Context) *GetDomainDomainParams {
	return &GetDomainDomainParams{
		Context: ctx,
	}
}

// NewGetDomainDomainParamsWithHTTPClient creates a new GetDomainDomainParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDomainDomainParamsWithHTTPClient(client *http.Client) *GetDomainDomainParams {
	return &GetDomainDomainParams{
		HTTPClient: client,
	}
}

/*
GetDomainDomainParams contains all the parameters to send to the API endpoint

	for the get domain domain operation.

	Typically these are written to a http.Request.
*/
type GetDomainDomainParams struct {

	/* Domain.

	   domain
	*/
	Domain string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get domain domain params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDomainDomainParams) WithDefaults() *GetDomainDomainParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get domain domain params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDomainDomainParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get domain domain params
func (o *GetDomainDomainParams) WithTimeout(timeout time.Duration) *GetDomainDomainParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get domain domain params
func (o *GetDomainDomainParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get domain domain params
func (o *GetDomainDomainParams) WithContext(ctx context.Context) *GetDomainDomainParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get domain domain params
func (o *GetDomainDomainParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get domain domain params
func (o *GetDomainDomainParams) WithHTTPClient(client *http.Client) *GetDomainDomainParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get domain domain params
func (o *GetDomainDomainParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomain adds the domain to the get domain domain params
func (o *GetDomainDomainParams) WithDomain(domain string) *GetDomainDomainParams {
	o.SetDomain(domain)
	return o
}

// SetDomain adds the domain to the get domain domain params
func (o *GetDomainDomainParams) SetDomain(domain string) {
	o.Domain = domain
}

// WriteToRequest writes these params to a swagger request
func (o *GetDomainDomainParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param domain
	if err := r.SetPathParam("domain", o.Domain); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
