// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteRegistryFunctionNameTagParams creates a new DeleteRegistryFunctionNameTagParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteRegistryFunctionNameTagParams() *DeleteRegistryFunctionNameTagParams {
	return &DeleteRegistryFunctionNameTagParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteRegistryFunctionNameTagParamsWithTimeout creates a new DeleteRegistryFunctionNameTagParams object
// with the ability to set a timeout on a request.
func NewDeleteRegistryFunctionNameTagParamsWithTimeout(timeout time.Duration) *DeleteRegistryFunctionNameTagParams {
	return &DeleteRegistryFunctionNameTagParams{
		timeout: timeout,
	}
}

// NewDeleteRegistryFunctionNameTagParamsWithContext creates a new DeleteRegistryFunctionNameTagParams object
// with the ability to set a context for a request.
func NewDeleteRegistryFunctionNameTagParamsWithContext(ctx context.Context) *DeleteRegistryFunctionNameTagParams {
	return &DeleteRegistryFunctionNameTagParams{
		Context: ctx,
	}
}

// NewDeleteRegistryFunctionNameTagParamsWithHTTPClient creates a new DeleteRegistryFunctionNameTagParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteRegistryFunctionNameTagParamsWithHTTPClient(client *http.Client) *DeleteRegistryFunctionNameTagParams {
	return &DeleteRegistryFunctionNameTagParams{
		HTTPClient: client,
	}
}

/*
DeleteRegistryFunctionNameTagParams contains all the parameters to send to the API endpoint

	for the delete registry function name tag operation.

	Typically these are written to a http.Request.
*/
type DeleteRegistryFunctionNameTagParams struct {

	/* Name.

	   name
	*/
	Name string

	/* Tag.

	   tag
	*/
	Tag string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete registry function name tag params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteRegistryFunctionNameTagParams) WithDefaults() *DeleteRegistryFunctionNameTagParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete registry function name tag params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteRegistryFunctionNameTagParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete registry function name tag params
func (o *DeleteRegistryFunctionNameTagParams) WithTimeout(timeout time.Duration) *DeleteRegistryFunctionNameTagParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete registry function name tag params
func (o *DeleteRegistryFunctionNameTagParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete registry function name tag params
func (o *DeleteRegistryFunctionNameTagParams) WithContext(ctx context.Context) *DeleteRegistryFunctionNameTagParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete registry function name tag params
func (o *DeleteRegistryFunctionNameTagParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete registry function name tag params
func (o *DeleteRegistryFunctionNameTagParams) WithHTTPClient(client *http.Client) *DeleteRegistryFunctionNameTagParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete registry function name tag params
func (o *DeleteRegistryFunctionNameTagParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete registry function name tag params
func (o *DeleteRegistryFunctionNameTagParams) WithName(name string) *DeleteRegistryFunctionNameTagParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete registry function name tag params
func (o *DeleteRegistryFunctionNameTagParams) SetName(name string) {
	o.Name = name
}

// WithTag adds the tag to the delete registry function name tag params
func (o *DeleteRegistryFunctionNameTagParams) WithTag(tag string) *DeleteRegistryFunctionNameTagParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the delete registry function name tag params
func (o *DeleteRegistryFunctionNameTagParams) SetTag(tag string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteRegistryFunctionNameTagParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param tag
	if err := r.SetPathParam("tag", o.Tag); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
