// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRegistryFunctionNameTagParams creates a new GetRegistryFunctionNameTagParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRegistryFunctionNameTagParams() *GetRegistryFunctionNameTagParams {
	return &GetRegistryFunctionNameTagParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRegistryFunctionNameTagParamsWithTimeout creates a new GetRegistryFunctionNameTagParams object
// with the ability to set a timeout on a request.
func NewGetRegistryFunctionNameTagParamsWithTimeout(timeout time.Duration) *GetRegistryFunctionNameTagParams {
	return &GetRegistryFunctionNameTagParams{
		timeout: timeout,
	}
}

// NewGetRegistryFunctionNameTagParamsWithContext creates a new GetRegistryFunctionNameTagParams object
// with the ability to set a context for a request.
func NewGetRegistryFunctionNameTagParamsWithContext(ctx context.Context) *GetRegistryFunctionNameTagParams {
	return &GetRegistryFunctionNameTagParams{
		Context: ctx,
	}
}

// NewGetRegistryFunctionNameTagParamsWithHTTPClient creates a new GetRegistryFunctionNameTagParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRegistryFunctionNameTagParamsWithHTTPClient(client *http.Client) *GetRegistryFunctionNameTagParams {
	return &GetRegistryFunctionNameTagParams{
		HTTPClient: client,
	}
}

/*
GetRegistryFunctionNameTagParams contains all the parameters to send to the API endpoint

	for the get registry function name tag operation.

	Typically these are written to a http.Request.
*/
type GetRegistryFunctionNameTagParams struct {

	/* Name.

	   name
	*/
	Name string

	/* Tag.

	   tag
	*/
	Tag string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get registry function name tag params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRegistryFunctionNameTagParams) WithDefaults() *GetRegistryFunctionNameTagParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get registry function name tag params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRegistryFunctionNameTagParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get registry function name tag params
func (o *GetRegistryFunctionNameTagParams) WithTimeout(timeout time.Duration) *GetRegistryFunctionNameTagParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get registry function name tag params
func (o *GetRegistryFunctionNameTagParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get registry function name tag params
func (o *GetRegistryFunctionNameTagParams) WithContext(ctx context.Context) *GetRegistryFunctionNameTagParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get registry function name tag params
func (o *GetRegistryFunctionNameTagParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get registry function name tag params
func (o *GetRegistryFunctionNameTagParams) WithHTTPClient(client *http.Client) *GetRegistryFunctionNameTagParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get registry function name tag params
func (o *GetRegistryFunctionNameTagParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get registry function name tag params
func (o *GetRegistryFunctionNameTagParams) WithName(name string) *GetRegistryFunctionNameTagParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get registry function name tag params
func (o *GetRegistryFunctionNameTagParams) SetName(name string) {
	o.Name = name
}

// WithTag adds the tag to the get registry function name tag params
func (o *GetRegistryFunctionNameTagParams) WithTag(tag string) *GetRegistryFunctionNameTagParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the get registry function name tag params
func (o *GetRegistryFunctionNameTagParams) SetTag(tag string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *GetRegistryFunctionNameTagParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param tag
	if err := r.SetPathParam("tag", o.Tag); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
