// Code generated by go-swagger; DO NOT EDIT.

package deploy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteDeployFunctionIdentifierReader is a Reader for the DeleteDeployFunctionIdentifier structure.
type DeleteDeployFunctionIdentifierReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDeployFunctionIdentifierReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteDeployFunctionIdentifierOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteDeployFunctionIdentifierBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteDeployFunctionIdentifierUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteDeployFunctionIdentifierNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteDeployFunctionIdentifierInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteDeployFunctionIdentifierOK creates a DeleteDeployFunctionIdentifierOK with default headers values
func NewDeleteDeployFunctionIdentifierOK() *DeleteDeployFunctionIdentifierOK {
	return &DeleteDeployFunctionIdentifierOK{}
}

/*
DeleteDeployFunctionIdentifierOK describes a response with status code 200, with default header values.

OK
*/
type DeleteDeployFunctionIdentifierOK struct {
	Payload string
}

// IsSuccess returns true when this delete deploy function identifier o k response has a 2xx status code
func (o *DeleteDeployFunctionIdentifierOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete deploy function identifier o k response has a 3xx status code
func (o *DeleteDeployFunctionIdentifierOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete deploy function identifier o k response has a 4xx status code
func (o *DeleteDeployFunctionIdentifierOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete deploy function identifier o k response has a 5xx status code
func (o *DeleteDeployFunctionIdentifierOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete deploy function identifier o k response a status code equal to that given
func (o *DeleteDeployFunctionIdentifierOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete deploy function identifier o k response
func (o *DeleteDeployFunctionIdentifierOK) Code() int {
	return 200
}

func (o *DeleteDeployFunctionIdentifierOK) Error() string {
	return fmt.Sprintf("[DELETE /deploy/function/{identifier}][%d] deleteDeployFunctionIdentifierOK  %+v", 200, o.Payload)
}

func (o *DeleteDeployFunctionIdentifierOK) String() string {
	return fmt.Sprintf("[DELETE /deploy/function/{identifier}][%d] deleteDeployFunctionIdentifierOK  %+v", 200, o.Payload)
}

func (o *DeleteDeployFunctionIdentifierOK) GetPayload() string {
	return o.Payload
}

func (o *DeleteDeployFunctionIdentifierOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDeployFunctionIdentifierBadRequest creates a DeleteDeployFunctionIdentifierBadRequest with default headers values
func NewDeleteDeployFunctionIdentifierBadRequest() *DeleteDeployFunctionIdentifierBadRequest {
	return &DeleteDeployFunctionIdentifierBadRequest{}
}

/*
DeleteDeployFunctionIdentifierBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeleteDeployFunctionIdentifierBadRequest struct {
	Payload string
}

// IsSuccess returns true when this delete deploy function identifier bad request response has a 2xx status code
func (o *DeleteDeployFunctionIdentifierBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete deploy function identifier bad request response has a 3xx status code
func (o *DeleteDeployFunctionIdentifierBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete deploy function identifier bad request response has a 4xx status code
func (o *DeleteDeployFunctionIdentifierBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete deploy function identifier bad request response has a 5xx status code
func (o *DeleteDeployFunctionIdentifierBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete deploy function identifier bad request response a status code equal to that given
func (o *DeleteDeployFunctionIdentifierBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete deploy function identifier bad request response
func (o *DeleteDeployFunctionIdentifierBadRequest) Code() int {
	return 400
}

func (o *DeleteDeployFunctionIdentifierBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /deploy/function/{identifier}][%d] deleteDeployFunctionIdentifierBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteDeployFunctionIdentifierBadRequest) String() string {
	return fmt.Sprintf("[DELETE /deploy/function/{identifier}][%d] deleteDeployFunctionIdentifierBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteDeployFunctionIdentifierBadRequest) GetPayload() string {
	return o.Payload
}

func (o *DeleteDeployFunctionIdentifierBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDeployFunctionIdentifierUnauthorized creates a DeleteDeployFunctionIdentifierUnauthorized with default headers values
func NewDeleteDeployFunctionIdentifierUnauthorized() *DeleteDeployFunctionIdentifierUnauthorized {
	return &DeleteDeployFunctionIdentifierUnauthorized{}
}

/*
DeleteDeployFunctionIdentifierUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteDeployFunctionIdentifierUnauthorized struct {
	Payload string
}

// IsSuccess returns true when this delete deploy function identifier unauthorized response has a 2xx status code
func (o *DeleteDeployFunctionIdentifierUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete deploy function identifier unauthorized response has a 3xx status code
func (o *DeleteDeployFunctionIdentifierUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete deploy function identifier unauthorized response has a 4xx status code
func (o *DeleteDeployFunctionIdentifierUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete deploy function identifier unauthorized response has a 5xx status code
func (o *DeleteDeployFunctionIdentifierUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete deploy function identifier unauthorized response a status code equal to that given
func (o *DeleteDeployFunctionIdentifierUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete deploy function identifier unauthorized response
func (o *DeleteDeployFunctionIdentifierUnauthorized) Code() int {
	return 401
}

func (o *DeleteDeployFunctionIdentifierUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /deploy/function/{identifier}][%d] deleteDeployFunctionIdentifierUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteDeployFunctionIdentifierUnauthorized) String() string {
	return fmt.Sprintf("[DELETE /deploy/function/{identifier}][%d] deleteDeployFunctionIdentifierUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteDeployFunctionIdentifierUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *DeleteDeployFunctionIdentifierUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDeployFunctionIdentifierNotFound creates a DeleteDeployFunctionIdentifierNotFound with default headers values
func NewDeleteDeployFunctionIdentifierNotFound() *DeleteDeployFunctionIdentifierNotFound {
	return &DeleteDeployFunctionIdentifierNotFound{}
}

/*
DeleteDeployFunctionIdentifierNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteDeployFunctionIdentifierNotFound struct {
	Payload string
}

// IsSuccess returns true when this delete deploy function identifier not found response has a 2xx status code
func (o *DeleteDeployFunctionIdentifierNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete deploy function identifier not found response has a 3xx status code
func (o *DeleteDeployFunctionIdentifierNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete deploy function identifier not found response has a 4xx status code
func (o *DeleteDeployFunctionIdentifierNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete deploy function identifier not found response has a 5xx status code
func (o *DeleteDeployFunctionIdentifierNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete deploy function identifier not found response a status code equal to that given
func (o *DeleteDeployFunctionIdentifierNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete deploy function identifier not found response
func (o *DeleteDeployFunctionIdentifierNotFound) Code() int {
	return 404
}

func (o *DeleteDeployFunctionIdentifierNotFound) Error() string {
	return fmt.Sprintf("[DELETE /deploy/function/{identifier}][%d] deleteDeployFunctionIdentifierNotFound  %+v", 404, o.Payload)
}

func (o *DeleteDeployFunctionIdentifierNotFound) String() string {
	return fmt.Sprintf("[DELETE /deploy/function/{identifier}][%d] deleteDeployFunctionIdentifierNotFound  %+v", 404, o.Payload)
}

func (o *DeleteDeployFunctionIdentifierNotFound) GetPayload() string {
	return o.Payload
}

func (o *DeleteDeployFunctionIdentifierNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDeployFunctionIdentifierInternalServerError creates a DeleteDeployFunctionIdentifierInternalServerError with default headers values
func NewDeleteDeployFunctionIdentifierInternalServerError() *DeleteDeployFunctionIdentifierInternalServerError {
	return &DeleteDeployFunctionIdentifierInternalServerError{}
}

/*
DeleteDeployFunctionIdentifierInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteDeployFunctionIdentifierInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this delete deploy function identifier internal server error response has a 2xx status code
func (o *DeleteDeployFunctionIdentifierInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete deploy function identifier internal server error response has a 3xx status code
func (o *DeleteDeployFunctionIdentifierInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete deploy function identifier internal server error response has a 4xx status code
func (o *DeleteDeployFunctionIdentifierInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete deploy function identifier internal server error response has a 5xx status code
func (o *DeleteDeployFunctionIdentifierInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete deploy function identifier internal server error response a status code equal to that given
func (o *DeleteDeployFunctionIdentifierInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete deploy function identifier internal server error response
func (o *DeleteDeployFunctionIdentifierInternalServerError) Code() int {
	return 500
}

func (o *DeleteDeployFunctionIdentifierInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /deploy/function/{identifier}][%d] deleteDeployFunctionIdentifierInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteDeployFunctionIdentifierInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /deploy/function/{identifier}][%d] deleteDeployFunctionIdentifierInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteDeployFunctionIdentifierInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *DeleteDeployFunctionIdentifierInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
