// Code generated by go-swagger; DO NOT EDIT.

package cloud

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/loopholelabs/scale/cli/client/models"
)

// NewPostCloudDetachParams creates a new PostCloudDetachParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostCloudDetachParams() *PostCloudDetachParams {
	return &PostCloudDetachParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostCloudDetachParamsWithTimeout creates a new PostCloudDetachParams object
// with the ability to set a timeout on a request.
func NewPostCloudDetachParamsWithTimeout(timeout time.Duration) *PostCloudDetachParams {
	return &PostCloudDetachParams{
		timeout: timeout,
	}
}

// NewPostCloudDetachParamsWithContext creates a new PostCloudDetachParams object
// with the ability to set a context for a request.
func NewPostCloudDetachParamsWithContext(ctx context.Context) *PostCloudDetachParams {
	return &PostCloudDetachParams{
		Context: ctx,
	}
}

// NewPostCloudDetachParamsWithHTTPClient creates a new PostCloudDetachParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostCloudDetachParamsWithHTTPClient(client *http.Client) *PostCloudDetachParams {
	return &PostCloudDetachParams{
		HTTPClient: client,
	}
}

/*
PostCloudDetachParams contains all the parameters to send to the API endpoint

	for the post cloud detach operation.

	Typically these are written to a http.Request.
*/
type PostCloudDetachParams struct {

	/* Request.

	   Detach Domain Request
	*/
	Request *models.ModelsDetachDomainRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post cloud detach params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCloudDetachParams) WithDefaults() *PostCloudDetachParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post cloud detach params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCloudDetachParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post cloud detach params
func (o *PostCloudDetachParams) WithTimeout(timeout time.Duration) *PostCloudDetachParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post cloud detach params
func (o *PostCloudDetachParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post cloud detach params
func (o *PostCloudDetachParams) WithContext(ctx context.Context) *PostCloudDetachParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post cloud detach params
func (o *PostCloudDetachParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post cloud detach params
func (o *PostCloudDetachParams) WithHTTPClient(client *http.Client) *PostCloudDetachParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post cloud detach params
func (o *PostCloudDetachParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post cloud detach params
func (o *PostCloudDetachParams) WithRequest(request *models.ModelsDetachDomainRequest) *PostCloudDetachParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post cloud detach params
func (o *PostCloudDetachParams) SetRequest(request *models.ModelsDetachDomainRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostCloudDetachParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
