// Code generated by scale-signature-go v0.0.1, DO NOT EDIT.
// source: signature/Bad/signature.proto

package bad

import (
	"errors"
	"github.com/loopholelabs/polyglot-go"
)

var (
	NilDecode = errors.New("cannot decode into a nil root struct")
)

type BadContext struct {
	Data uint32
}

func NewBadContext() *BadContext {
	return &BadContext{}
}

func (x *BadContext) error(b *polyglot.Buffer, err error) {
	polyglot.Encoder(b).Error(err)
}

func (x *BadContext) internalEncode(b *polyglot.Buffer) {
	if x == nil {
		polyglot.Encoder(b).Nil()
	} else {
		polyglot.Encoder(b).Uint32(x.Data)
	}
}

func (x *BadContext) internalDecode(b []byte) error {
	if x == nil {
		return NilDecode
	}
	d := polyglot.GetDecoder(b)
	defer d.Return()
	return x.decode(d)
}

func (x *BadContext) decode(d *polyglot.Decoder) error {
	if d.Nil() {
		return nil
	}

	err, _ := d.Error()
	if err != nil {
		return err
	}
	x.Data, err = d.Uint32()
	if err != nil {
		return err
	}
	return nil
}
