// Code generated by scale-extension v0.4.8, DO NOT EDIT.
// output: local_inttest_latest_guest

package local_inttest_latest_guest

// Interface must be implemented by the host.
type Interface interface {
	New(params *Stringval) (Example, error)

	World(params *Stringval) (Stringval, error)
}

type Example interface {
	Hello(*Stringval) (Stringval, error)
}
