// Code generated by scale-go v0.1.0, DO NOT EDIT.
// schema: example:latest

package main

import (
	scale "example"
	"signature"
)

// needed to satisfy compiler
func main() {}

//export initialize
func initialize() uint64 {

	return 0
}

//export run
func run() uint64 {
	var err error
	ctx := signature.NewExample()
	ctx, err = signature.Read(ctx)
	if err != nil {
		return packUint32(signature.Error(err))
	}
	ctx, err = scale.Example(ctx)
	if err != nil {
		return packUint32(signature.Error(err))
	}
	return packUint32(signature.Write(ctx))
}

//export resize
func resize(size uint32) uint32 {
	return signature.Resize(size)
}

//export hash
func hash() uint64 {
	return packUint32(signature.Hash())
}

func packUint32(offset uint32, length uint32) uint64 {
	return uint64(offset)<<32 | uint64(length)
}
