// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRegistryFunctionOrganizationParams creates a new GetRegistryFunctionOrganizationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRegistryFunctionOrganizationParams() *GetRegistryFunctionOrganizationParams {
	return &GetRegistryFunctionOrganizationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRegistryFunctionOrganizationParamsWithTimeout creates a new GetRegistryFunctionOrganizationParams object
// with the ability to set a timeout on a request.
func NewGetRegistryFunctionOrganizationParamsWithTimeout(timeout time.Duration) *GetRegistryFunctionOrganizationParams {
	return &GetRegistryFunctionOrganizationParams{
		timeout: timeout,
	}
}

// NewGetRegistryFunctionOrganizationParamsWithContext creates a new GetRegistryFunctionOrganizationParams object
// with the ability to set a context for a request.
func NewGetRegistryFunctionOrganizationParamsWithContext(ctx context.Context) *GetRegistryFunctionOrganizationParams {
	return &GetRegistryFunctionOrganizationParams{
		Context: ctx,
	}
}

// NewGetRegistryFunctionOrganizationParamsWithHTTPClient creates a new GetRegistryFunctionOrganizationParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRegistryFunctionOrganizationParamsWithHTTPClient(client *http.Client) *GetRegistryFunctionOrganizationParams {
	return &GetRegistryFunctionOrganizationParams{
		HTTPClient: client,
	}
}

/*
GetRegistryFunctionOrganizationParams contains all the parameters to send to the API endpoint

	for the get registry function organization operation.

	Typically these are written to a http.Request.
*/
type GetRegistryFunctionOrganizationParams struct {

	/* Organization.

	   organization
	*/
	Organization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get registry function organization params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRegistryFunctionOrganizationParams) WithDefaults() *GetRegistryFunctionOrganizationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get registry function organization params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRegistryFunctionOrganizationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get registry function organization params
func (o *GetRegistryFunctionOrganizationParams) WithTimeout(timeout time.Duration) *GetRegistryFunctionOrganizationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get registry function organization params
func (o *GetRegistryFunctionOrganizationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get registry function organization params
func (o *GetRegistryFunctionOrganizationParams) WithContext(ctx context.Context) *GetRegistryFunctionOrganizationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get registry function organization params
func (o *GetRegistryFunctionOrganizationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get registry function organization params
func (o *GetRegistryFunctionOrganizationParams) WithHTTPClient(client *http.Client) *GetRegistryFunctionOrganizationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get registry function organization params
func (o *GetRegistryFunctionOrganizationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganization adds the organization to the get registry function organization params
func (o *GetRegistryFunctionOrganizationParams) WithOrganization(organization string) *GetRegistryFunctionOrganizationParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the get registry function organization params
func (o *GetRegistryFunctionOrganizationParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WriteToRequest writes these params to a swagger request
func (o *GetRegistryFunctionOrganizationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
