// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsAttachDomainRequest models attach domain request
//
// swagger:model models.AttachDomainRequest
type ModelsAttachDomainRequest struct {

	// deployment
	Deployment string `json:"deployment,omitempty"`

	// domain
	Domain string `json:"domain,omitempty"`

	// force
	Force bool `json:"force,omitempty"`
}

// Validate validates this models attach domain request
func (m *ModelsAttachDomainRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models attach domain request based on context it is used
func (m *ModelsAttachDomainRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsAttachDomainRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsAttachDomainRequest) UnmarshalBinary(b []byte) error {
	var res ModelsAttachDomainRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
