// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsSignatureResponse models signature response
//
// swagger:model models.SignatureResponse
type ModelsSignatureResponse struct {

	// golang import path guest
	GolangImportPathGuest string `json:"golang_import_path_guest,omitempty"`

	// golang import path host
	GolangImportPathHost string `json:"golang_import_path_host,omitempty"`

	// hash
	Hash string `json:"hash,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// organization
	Organization string `json:"organization,omitempty"`

	// public
	Public bool `json:"public,omitempty"`

	// tag
	Tag string `json:"tag,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this models signature response
func (m *ModelsSignatureResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models signature response based on context it is used
func (m *ModelsSignatureResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsSignatureResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsSignatureResponse) UnmarshalBinary(b []byte) error {
	var res ModelsSignatureResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
