// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsCreateFunctionResponse models create function response
//
// swagger:model models.CreateFunctionResponse
type ModelsCreateFunctionResponse struct {

	// hash
	Hash string `json:"hash,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// organization
	Organization string `json:"organization,omitempty"`

	// public
	Public bool `json:"public,omitempty"`

	// tag
	Tag string `json:"tag,omitempty"`
}

// Validate validates this models create function response
func (m *ModelsCreateFunctionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models create function response based on context it is used
func (m *ModelsCreateFunctionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsCreateFunctionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsCreateFunctionResponse) UnmarshalBinary(b []byte) error {
	var res ModelsCreateFunctionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
