// Code generated by go-swagger; DO NOT EDIT.

package deploy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new deploy API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for deploy API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteDeployFunctionIdentifier(params *DeleteDeployFunctionIdentifierParams, opts ...ClientOption) (*DeleteDeployFunctionIdentifierOK, error)

	PostDeployFunction(params *PostDeployFunctionParams, opts ...ClientOption) (*PostDeployFunctionOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteDeployFunctionIdentifier Removes a deployed function from the servers
*/
func (a *Client) DeleteDeployFunctionIdentifier(params *DeleteDeployFunctionIdentifierParams, opts ...ClientOption) (*DeleteDeployFunctionIdentifierOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteDeployFunctionIdentifierParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteDeployFunctionIdentifier",
		Method:             "DELETE",
		PathPattern:        "/deploy/function/{identifier}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteDeployFunctionIdentifierReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteDeployFunctionIdentifierOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteDeployFunctionIdentifier: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostDeployFunction Deploys a scale function
*/
func (a *Client) PostDeployFunction(params *PostDeployFunctionParams, opts ...ClientOption) (*PostDeployFunctionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostDeployFunctionParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostDeployFunction",
		Method:             "POST",
		PathPattern:        "/deploy/function",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"multipart/form-data"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostDeployFunctionReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostDeployFunctionOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostDeployFunction: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
