// Code generated by scale-extension 0.4.5, DO NOT EDIT.
// output: local_inttest_latest_guest

export * from "./types";

// Define any global functions here...

export declare function New(params: types.Stringval): types.Example;

export declare function World(params: types.Stringval): types.Stringval;

