// Code generated by go-swagger; DO NOT EDIT.

package access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAccessApikeyNameParams creates a new PostAccessApikeyNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAccessApikeyNameParams() *PostAccessApikeyNameParams {
	return &PostAccessApikeyNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAccessApikeyNameParamsWithTimeout creates a new PostAccessApikeyNameParams object
// with the ability to set a timeout on a request.
func NewPostAccessApikeyNameParamsWithTimeout(timeout time.Duration) *PostAccessApikeyNameParams {
	return &PostAccessApikeyNameParams{
		timeout: timeout,
	}
}

// NewPostAccessApikeyNameParamsWithContext creates a new PostAccessApikeyNameParams object
// with the ability to set a context for a request.
func NewPostAccessApikeyNameParamsWithContext(ctx context.Context) *PostAccessApikeyNameParams {
	return &PostAccessApikeyNameParams{
		Context: ctx,
	}
}

// NewPostAccessApikeyNameParamsWithHTTPClient creates a new PostAccessApikeyNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAccessApikeyNameParamsWithHTTPClient(client *http.Client) *PostAccessApikeyNameParams {
	return &PostAccessApikeyNameParams{
		HTTPClient: client,
	}
}

/*
PostAccessApikeyNameParams contains all the parameters to send to the API endpoint

	for the post access apikey name operation.

	Typically these are written to a http.Request.
*/
type PostAccessApikeyNameParams struct {

	/* Name.

	   name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post access apikey name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAccessApikeyNameParams) WithDefaults() *PostAccessApikeyNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post access apikey name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAccessApikeyNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post access apikey name params
func (o *PostAccessApikeyNameParams) WithTimeout(timeout time.Duration) *PostAccessApikeyNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post access apikey name params
func (o *PostAccessApikeyNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post access apikey name params
func (o *PostAccessApikeyNameParams) WithContext(ctx context.Context) *PostAccessApikeyNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post access apikey name params
func (o *PostAccessApikeyNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post access apikey name params
func (o *PostAccessApikeyNameParams) WithHTTPClient(client *http.Client) *PostAccessApikeyNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post access apikey name params
func (o *PostAccessApikeyNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the post access apikey name params
func (o *PostAccessApikeyNameParams) WithName(name string) *PostAccessApikeyNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the post access apikey name params
func (o *PostAccessApikeyNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PostAccessApikeyNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
