// Code generated by scale-extension 0.4.5, DO NOT EDIT.
// output: local-inttest-latest-host

import { Extension as ExtensionInterface } from "@loopholelabs/scale-extension-interfaces";

export * from "./types";

export declare function New(impl: Interface): ExtensionInterface;

// Interface to the extension impl. This is what the implementor should create

export declare interface Interface {
  New(params: Stringval): Example;

  World(params: Stringval): Stringval;

}

export declare interface Example {
  Hello(params: Stringval): Stringval;

}

