[package]
name = "jsbuilder-core"
version = "0.0.1"

[[bin]]
name = "jsbuilder_core"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
quickjs-wasm-sys = "0.1.1"
once_cell = "1.4.0"
lazy_static = "1.4.0"
