// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsUserInfoResponse models user info response
//
// swagger:model models.UserInfoResponse
type ModelsUserInfoResponse struct {

	// email
	Email string `json:"email,omitempty"`

	// organization
	Organization string `json:"organization,omitempty"`

	// organizations
	Organizations []string `json:"organizations"`
}

// Validate validates this models user info response
func (m *ModelsUserInfoResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models user info response based on context it is used
func (m *ModelsUserInfoResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsUserInfoResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsUserInfoResponse) UnmarshalBinary(b []byte) error {
	var res ModelsUserInfoResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
