// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsDeploymentResponse models deployment response
//
// swagger:model models.DeploymentResponse
type ModelsDeploymentResponse struct {

	// attached domain
	AttachedDomain []string `json:"attached_domain"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// functions
	Functions []*ModelsFunctionResponse `json:"functions"`

	// identifier
	Identifier string `json:"identifier,omitempty"`

	// root domain
	RootDomain string `json:"root_domain,omitempty"`

	// subdomain
	Subdomain string `json:"subdomain,omitempty"`
}

// Validate validates this models deployment response
func (m *ModelsDeploymentResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFunctions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsDeploymentResponse) validateFunctions(formats strfmt.Registry) error {
	if swag.IsZero(m.Functions) { // not required
		return nil
	}

	for i := 0; i < len(m.Functions); i++ {
		if swag.IsZero(m.Functions[i]) { // not required
			continue
		}

		if m.Functions[i] != nil {
			if err := m.Functions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("functions" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("functions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this models deployment response based on the context it is used
func (m *ModelsDeploymentResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFunctions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsDeploymentResponse) contextValidateFunctions(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Functions); i++ {

		if m.Functions[i] != nil {

			if swag.IsZero(m.Functions[i]) { // not required
				return nil
			}

			if err := m.Functions[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("functions" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("functions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelsDeploymentResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsDeploymentResponse) UnmarshalBinary(b []byte) error {
	var res ModelsDeploymentResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
