[package]
name = "jsbuilder"
version = "0.0.1"
build = "build.rs"

[[bin]]
name = "jsbuilder"

[dependencies]
wizer = { git = "https://github.com/bytecodealliance/wizer", branch = "main" }
which = "4.2"
structopt = "0.3"
anyhow = "1.0"
tempfile = "3.2.0"
binaryen = "0.12.0"

[dev-dependencies]
wasmtime = "0.34.2"
wasmtime-wasi = "0.34.2"
wasi-common = "0.34.2"
serde_json = "1.0"
uuid = { version = "0.8", features = ["v4"] }
lazy_static = "1.4"
serde = { version = "1.0", default-features = false, features = ["derive"] }
