name: npm CI

on: [push, pull_request]

jobs:
  npm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - name: Cache the dependency directories
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: npm
      - name: Install dependencies with npm
        run: npm install --legacy-peer-deps --include=dev
      - name: Build with npm
        run: npm run build
      - name: Publish to npm
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: JS-DevTools/npm-publish@v1
        with:
          package: ./package.json
          path: ./
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          access: "public"
