name: release-macos-JSBuilder

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ATiltedTree/setup-rust@v1
        with:
          targets: x86_64-apple-darwin
          rust-version: nightly
      - uses: mbround18/setup-osxcross@v1
        with:
          osx-version: "12.3"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-wasi
          override: true
          components: rustfmt, clippy
      - name: Install wasi
        working-directory: ts/compile/builder
        run: ./install-wasi-sdk.sh
      - name: Build jsbuilder
        working-directory: ts/compile/builder
        run: make cli-mac
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./ts/compile/builder/target/release/jsbuilder
