// Code generated by go-swagger; DO NOT EDIT.

package access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAccessApikeyNameParams creates a new GetAccessApikeyNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAccessApikeyNameParams() *GetAccessApikeyNameParams {
	return &GetAccessApikeyNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAccessApikeyNameParamsWithTimeout creates a new GetAccessApikeyNameParams object
// with the ability to set a timeout on a request.
func NewGetAccessApikeyNameParamsWithTimeout(timeout time.Duration) *GetAccessApikeyNameParams {
	return &GetAccessApikeyNameParams{
		timeout: timeout,
	}
}

// NewGetAccessApikeyNameParamsWithContext creates a new GetAccessApikeyNameParams object
// with the ability to set a context for a request.
func NewGetAccessApikeyNameParamsWithContext(ctx context.Context) *GetAccessApikeyNameParams {
	return &GetAccessApikeyNameParams{
		Context: ctx,
	}
}

// NewGetAccessApikeyNameParamsWithHTTPClient creates a new GetAccessApikeyNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAccessApikeyNameParamsWithHTTPClient(client *http.Client) *GetAccessApikeyNameParams {
	return &GetAccessApikeyNameParams{
		HTTPClient: client,
	}
}

/*
GetAccessApikeyNameParams contains all the parameters to send to the API endpoint

	for the get access apikey name operation.

	Typically these are written to a http.Request.
*/
type GetAccessApikeyNameParams struct {

	/* Name.

	   API Key Name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get access apikey name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAccessApikeyNameParams) WithDefaults() *GetAccessApikeyNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get access apikey name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAccessApikeyNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get access apikey name params
func (o *GetAccessApikeyNameParams) WithTimeout(timeout time.Duration) *GetAccessApikeyNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get access apikey name params
func (o *GetAccessApikeyNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get access apikey name params
func (o *GetAccessApikeyNameParams) WithContext(ctx context.Context) *GetAccessApikeyNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get access apikey name params
func (o *GetAccessApikeyNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get access apikey name params
func (o *GetAccessApikeyNameParams) WithHTTPClient(client *http.Client) *GetAccessApikeyNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get access apikey name params
func (o *GetAccessApikeyNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get access apikey name params
func (o *GetAccessApikeyNameParams) WithName(name string) *GetAccessApikeyNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get access apikey name params
func (o *GetAccessApikeyNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetAccessApikeyNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
